name: Development
on:
  pull_request:
    branches:
      - "**"

jobs:
  lint_and_format:
    name: Linting and formatting checks
    uses: ./.github/workflows/lint-and-format.yml

  # build:
  #   needs: lint_and_format
  #   name: Build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     # TODO
